<script>
	import Slider from "../../components/Slider.svelte";

	import Image1 from "./1.jpg";
	import Image2 from "./2.jpg";
	import Image3 from "./3.jpg";
	import Image4 from "./4.jpg";
	import Image5 from "./5.jpg";
	import Image6 from "./6.jpg";
	import Image7 from "./7.jpg";
	import Image8 from "./8.jpg";
	import Image9 from "./9.jpg";

	const images = [Image3, Image4];
	const images2 = [Image5, Image6, Image7];
</script>

<img srcset={Image1} alt="Image1" />
<img srcset={Image2} alt="Image2" />

<p>
	This project started out as a way for me to experiment with the visual
	representation of an encyclopedia. The reason being that my research thesis
	aims to answer the question: How can we facilitate the findings of
	compelling stories in emergent narrative games that employ procedural
	generation? To briefly summarize my question and its context, I want to make
	it easier for players to experience and discover compelling stories produced
	in a game. To do so, I planned on using an encyclopedia which consists of an
	interface that will contain all the information generated by the game. This
	interface would allow users to sift through the data as if it was a
	Wikipedia article with multiple hyperlinks connecting pages together.
</p>

<p>
	My first proposition was to integrate the web and mobile application design
	mentality to my encyclopedia since I was mainly inspired by their large
	printed book format up to that point. However, a lack of clear direction and
	inspiration lead me to change my goal. I would instead shift my focus to the
	linear approach of books. I want to know how I can break the linear flow of
	readings and make it sporadic. This new direction resulted from my interest
	in the fragmented design aspect and various discussions with Miranda and my
	peers. I was introduced to the rhizome theory by Miranda and Harley and felt
	like it would be an ideal lead for me. I would experiment with the rhizome
	philosophy by fragmenting an encyclopedia’s content and turning the whole
	thing into a game.
</p>

<Slider {images} />

<p>
	So what is a rhizome? For Deleuze and Guattari, a rhizome is the opposite of
	a tree, but what do they mean by a tree? In this context, a tree refers to a
	hierarchical organization. You can think of a family tree or how we organize
	biological species where every end of a branch has a common ancestor. The
	principle of a rhizome is that it does not have a beginning or an end.
	According to Brent Atkins “rhizomes do not propagate by the way of clearly
	delineated hierarchies but by underground stems in which any part may send
	additional shoots upward, downward, or laterally.” In short, a rhizome does
	not have a hierarchy.
</p>

<p>
	A scheme where many elements can spread in any given direction with no clear
	beginning and ending gave me the idea to create fragments of the content
	present on a Wikipedia page and make a puzzle out of it. However, this
	puzzle shouldn’t have a correct order where if you align all the pieces, it
	will form a bigger picture. No, if it is to be a rhizome, any order should
	be suitable.
</p>

<p>
	Although I mainly focused on the chaotic nature of rhizome and their
	nonlinear functioning. For Deleuze and Guattari, they are more than that.
	According to them, rhizomes are the key to create the new. In their book <i
		>A Thousand Plateaux: Capitalism and Schizophrenia</i
	>, not only do they want to create new concepts, but they also want the
	readers to create new connections.
</p>

<p>
	I did not seek to make new concepts with what I have read and analyzed for
	my project. I just wanted to create a fun way of combing through disorganize
	elements. However, a case could be made that I managed to create something
	new by making a connection between rhizomes and games and puzzles and
	encyclopedia. Still, I am unable to prove any of these claims for my
	research was brief due to a tight schedule.
</p>

<p>
	I want to conclude on rhizomes with one last thing brought to my attention
	when discussing my direction for this project with Jonathan. He told me
	that, in a sense, wikis are already a rhizome in and of themselves. Thanks
	to their hyperlinks, articles are linked to one another and expand their
	body of knowledge. Creating new connections for every page conceived. Which
	means that my project is trying to produce a rhizome inside another rhizome,
	and I’m left wondering if the two would connect on the same level or if one
	is merely a part of the other?
</p>

<p>
	A large part of this project’s creative process was the brainstorming of
	ideas and directions. I hope that the previous sections gave a brief look at
	what I have been trying to wrap my head around for the past weeks, for there
	is too much to condense it all in this section.
</p>

<p>
	The first thing I decided to create was three sketches of puzzles. When
	creating these puzzles, I was thinking of movement, shuffling and
	deconstructing to break the linear flow specifically. The first one that
	came to mind was all about rotations, where three circles would overlap each
	other like a vein diagram and exchange their content. The second type of
	movement was translations, and I instantly thought about sliding puzzles.
	The third one is a mix of both, combining rotations and translations. If a
	user wanted to view a piece’s content, they would have to bring it to the
	golden square, the selector. All I had was a puzzle that would force users
	to solve them if they wanted to access the information. But it did not feel
	like a game, and I had the impression it would be more of a chore.
</p>

<Slider images={images2} />

<p>
	To solve this problem, I thought of adding an objective. Players would have
	a question that they could only answer by finding the solution somewhere in
	the puzzle. Now I needed to choose a puzzle, create it and adapt an article
	to it. Because of time constraints, I decided to pick the sliding puzzle as
	I felt it would be the easiest to do. I searched for an article on Wikipedia
	that I found interesting, wrote five questions about it and fragmented the
	content into 15 pieces.
</p>

<img srcset={Image8} alt="Image8" />

<p>
	My next step was to conceive the interface. I decided to create a
	high-fidelity prototype. This way, I could export the visuals for my
	interactive prototype. While designing the interface, I thought of
	additional things, such as how it would play, convey the information to
	users, and the tutorial. I went this much in detail because I had fun and
	wanted others to experience it.
</p>

<img srcset={Image9} alt="Image9" />

<p>
	Finally, it was time to make it. I imported all the visual assets from my
	high-fidelity prototype, programmed the possible interactions and exported
	an executable. Unfortunately, I could not make one that would work on Mac
	OS, and since I knew most people used one, I had to find an alternative. I
	created a version that could run on a web browser. However, you could not
	play it unless it was on a server, which is how I ended creating an account
	on Itch.io and uploading my project to the website. Now, if anyone wants to
	try it out, it is available at this link: <a href="https://beauanto.itch.io"
		>https://beauanto.itch.io</a
	>.
</p>
